### ISSUE TITLE
GIT PRO

### ISSUE THREAD

**Issue by emecas** [emecas/git-quips#1]
- [ ] Facts Collection for the SVN-GIT internal debate 
 [commit-it #20}(https://github.com/emecas/commitit/issues/20) 
- [x] Watch: Gittin' Git Session 
 [commit-it #2}(https://github.com/emecas/git-quips/issues/2) 
- [ ] Summarize: Gittin' Git Session 
 [commit-it #2}(https://github.com/emecas/git-quips/issues/2)
